"""Demo data for the Student 3 transport service.

Derived columns (``duration_minutes`` on options, ``estimated_cost`` on bookings)
are intentionally omitted here; the repository fills them through the same
helpers used by the write endpoints so seeded rows cannot drift from records
created through the API.

Trip identifiers mirror the Student 1 seed trips so the integrated demo shows
transport attached to trips that already exist in the shared application.
"""

SEED_TRANSPORT_OPTIONS = (
    {
        "id": "transport_2026_qf401_mel_syd",
        "type": "flight",
        "provider": "Qantas",
        "origin": "Melbourne",
        "destination": "Sydney",
        "departure_time": "2026-10-02T06:00",
        "arrival_time": "2026-10-02T07:35",
        "price": 189.00,
        "capacity": 180,
        "availability_status": "available",
        "notes": "Morning departure with checked baggage included.",
    },
    {
        "id": "transport_2026_qf436_syd_mel",
        "type": "flight",
        "provider": "Qantas",
        "origin": "Sydney",
        "destination": "Melbourne",
        "departure_time": "2026-10-05T18:20",
        "arrival_time": "2026-10-05T20:00",
        "price": 205.50,
        "capacity": 180,
        "availability_status": "available",
        "notes": "Return leg for the Sydney long weekend.",
    },
    {
        "id": "transport_2026_vline_mel_geelong",
        "type": "train",
        "provider": "V/Line",
        "origin": "Melbourne",
        "destination": "Geelong",
        "departure_time": "2026-11-13T08:15",
        "arrival_time": "2026-11-13T09:20",
        "price": 12.40,
        "capacity": 320,
        "availability_status": "available",
        "notes": "Regional service departing Southern Cross.",
    },
    {
        "id": "transport_2026_skybus_mel_city",
        "type": "bus",
        "provider": "SkyBus",
        "origin": "Melbourne Airport",
        "destination": "Melbourne CBD",
        "departure_time": "2026-11-12T10:30",
        "arrival_time": "2026-11-12T11:15",
        "price": 23.50,
        "capacity": 60,
        "availability_status": "limited",
        "notes": "Departs every 10 minutes; seats are not allocated.",
    },
    {
        "id": "transport_2027_jl772_syd_hnd",
        "type": "flight",
        "provider": "Japan Airlines",
        "origin": "Sydney",
        "destination": "Tokyo",
        "departure_time": "2027-03-28T21:35",
        "arrival_time": "2027-03-29T05:55",
        "departure_utc_offset": 660,
        "arrival_utc_offset": 540,
        "price": 1245.00,
        "capacity": 244,
        "availability_status": "available",
        "notes": "Overnight service arriving early morning.",
    },
    {
        "id": "transport_2027_nex_narita_tokyo",
        "type": "train",
        "provider": "JR East",
        "origin": "Narita Airport",
        "destination": "Tokyo Station",
        "departure_time": "2027-03-29T07:45",
        "arrival_time": "2027-03-29T08:48",
        "price": 32.00,
        "capacity": 400,
        "availability_status": "available",
        "notes": "Narita Express with reserved seating.",
    },
    {
        "id": "transport_2026_jq790_syd_ool",
        "type": "flight",
        "provider": "Jetstar",
        "origin": "Sydney",
        "destination": "Gold Coast",
        "departure_time": "2026-12-20T07:10",
        "arrival_time": "2026-12-20T08:35",
        "price": 149.90,
        "capacity": 186,
        "availability_status": "limited",
        "notes": "School holiday peak; baggage is sold separately.",
    },
    {
        "id": "transport_2026_europcar_gold_coast",
        "type": "car_rental",
        "provider": "Europcar",
        "origin": "Gold Coast Airport",
        "destination": "Gold Coast Airport",
        "departure_time": "2026-12-20T09:00",
        "arrival_time": "2026-12-27T09:00",
        "price": 612.00,
        "capacity": 5,
        "availability_status": "available",
        "notes": "Seven day SUV hire priced per vehicle rather than per seat.",
    },
    {
        "id": "transport_2027_zqn_snow_shuttle",
        "type": "transfer",
        "provider": "Queenstown Snow Shuttle",
        "origin": "Queenstown Airport",
        "destination": "Queenstown Town Centre",
        "departure_time": "2027-07-10T14:20",
        "arrival_time": "2027-07-10T14:55",
        "price": 28.00,
        "capacity": 11,
        "availability_status": "available",
        "notes": "Ski and board carriage included in the fare.",
    },
    {
        "id": "transport_2026_sq232_syd_sin",
        "type": "flight",
        "provider": "Singapore Airlines",
        "origin": "Sydney",
        "destination": "Singapore",
        "departure_time": "2026-09-01T10:15",
        "arrival_time": "2026-09-01T16:35",
        "departure_utc_offset": 600,
        "arrival_utc_offset": 480,
        "price": 878.40,
        "capacity": 253,
        "availability_status": "sold_out",
        "notes": "Cabin fully booked; waitlist only.",
    },
    {
        "id": "transport_2026_spirit_geelong_devonport",
        "type": "ferry",
        "provider": "Spirit of Tasmania",
        "origin": "Geelong",
        "destination": "Devonport",
        "departure_time": "2026-06-11T19:30",
        "arrival_time": "2026-06-12T06:00",
        "price": 289.00,
        "capacity": 1400,
        "availability_status": "available",
        "notes": "Overnight crossing with a cabin upgrade available.",
    },
    {
        "id": "transport_2027_xpt_syd_bne",
        "type": "train",
        "provider": "NSW TrainLink",
        "origin": "Sydney",
        "destination": "Brisbane",
        "departure_time": "2027-01-21T06:10",
        "arrival_time": "2027-01-21T20:25",
        "price": 132.00,
        "capacity": 220,
        "availability_status": "cancelled",
        "notes": "Service withdrawn for track maintenance.",
    },
    {
        "id": "transport_2026_qf777_syd_per",
        "type": "flight",
        "provider": "Qantas",
        "origin": "Sydney",
        "destination": "Perth",
        "departure_time": "2026-08-18T09:05",
        "arrival_time": "2026-08-18T12:10",
        "departure_utc_offset": 600,
        "arrival_utc_offset": 480,
        "price": 425.00,
        "capacity": 236,
        "availability_status": "available",
        "notes": "Wi-Fi equipped for the workcation leg.",
    },
    {
        "id": "transport_2027_adl_metro_bus",
        "type": "bus",
        "provider": "Adelaide Metro",
        "origin": "Adelaide Airport",
        "destination": "Adelaide CBD",
        "departure_time": "2027-02-26T13:40",
        "arrival_time": "2027-02-26T14:15",
        "price": 6.50,
        "capacity": 45,
        "availability_status": "available",
        "notes": "JetBus J1 route; fares are tapped on board.",
    },
)

SEED_TRANSPORT_BOOKINGS = (
    {
        "id": "booking_2026_sydney_outbound_flight",
        "trip_id": "trip_2026_sydney_long_weekend",
        "transport_id": "transport_2026_qf401_mel_syd",
        "traveller_count": 2,
        "booking_date": "2026-08-14",
        "booking_status": "confirmed",
        "notes": "Seats 14A and 14B requested.",
    },
    {
        "id": "booking_2026_sydney_return_flight",
        "trip_id": "trip_2026_sydney_long_weekend",
        "transport_id": "transport_2026_qf436_syd_mel",
        "traveller_count": 2,
        "booking_date": "2026-08-14",
        "booking_status": "confirmed",
        "notes": "Booked together with the outbound leg.",
    },
    {
        "id": "booking_2026_melbourne_skybus",
        "trip_id": "trip_2026_melbourne_food_trail",
        "transport_id": "transport_2026_skybus_mel_city",
        "traveller_count": 4,
        "booking_date": "2026-10-30",
        "booking_status": "confirmed",
        "notes": "Airport transfer on the arrival day.",
    },
    {
        "id": "booking_2026_melbourne_geelong_train",
        "trip_id": "trip_2026_melbourne_food_trail",
        "transport_id": "transport_2026_vline_mel_geelong",
        "traveller_count": 4,
        "booking_date": "2026-10-30",
        "booking_status": "pending",
        "notes": "Awaiting confirmation of the winery tour time.",
    },
    {
        "id": "booking_2027_tokyo_longhaul_flight",
        "trip_id": "trip_2027_tokyo_spring_visit",
        "transport_id": "transport_2027_jl772_syd_hnd",
        "traveller_count": 2,
        "booking_date": "2026-12-05",
        "booking_status": "confirmed",
        "notes": "Booked early for cherry blossom season.",
    },
    {
        "id": "booking_2027_tokyo_narita_express",
        "trip_id": "trip_2027_tokyo_spring_visit",
        "transport_id": "transport_2027_nex_narita_tokyo",
        "traveller_count": 2,
        "booking_date": "2027-01-18",
        "booking_status": "pending",
        "notes": "Collect tickets at the airport counter.",
    },
    {
        "id": "booking_2026_gold_coast_flight",
        "trip_id": "trip_2026_gold_coast_family_break",
        "transport_id": "transport_2026_jq790_syd_ool",
        "traveller_count": 5,
        "booking_date": "2026-09-19",
        "booking_status": "confirmed",
        "notes": "Two checked bags and a pram added.",
    },
    {
        "id": "booking_2026_gold_coast_car_hire",
        "trip_id": "trip_2026_gold_coast_family_break",
        "transport_id": "transport_2026_europcar_gold_coast",
        "traveller_count": 5,
        "booking_date": "2026-09-20",
        "booking_status": "confirmed",
        "estimated_cost": 612.00,
        "notes": "Priced per vehicle, so the per-traveller default is overridden.",
    },
    {
        "id": "booking_2027_queenstown_transfer",
        "trip_id": "trip_2027_queenstown_ski_escape",
        "transport_id": "transport_2027_zqn_snow_shuttle",
        "traveller_count": 3,
        "booking_date": "2027-05-02",
        "booking_status": "confirmed",
        "notes": "Ski carriage requested for three sets.",
    },
    {
        "id": "booking_2026_singapore_flight",
        "trip_id": "trip_2026_singapore_stopover",
        "transport_id": "transport_2026_sq232_syd_sin",
        "traveller_count": 1,
        "booking_date": "2026-05-30",
        "booking_status": "completed",
        "notes": "Flown before the cabin sold out.",
    },
    {
        "id": "booking_2026_hobart_ferry",
        "trip_id": "trip_2026_hobart_weekend_escape",
        "transport_id": "transport_2026_spirit_geelong_devonport",
        "traveller_count": 2,
        "booking_date": "2026-03-11",
        "booking_status": "completed",
        "notes": "Overnight cabin included.",
    },
    {
        "id": "booking_2027_brisbane_train",
        "trip_id": "trip_2027_brisbane_city_break",
        "transport_id": "transport_2027_xpt_syd_bne",
        "traveller_count": 2,
        "booking_date": "2026-11-20",
        "booking_status": "cancelled",
        "notes": "Cancelled when the service was withdrawn.",
    },
    {
        "id": "booking_2026_perth_flight",
        "trip_id": "trip_2026_perth_workcation",
        "transport_id": "transport_2026_qf777_syd_per",
        "traveller_count": 1,
        "booking_date": "2026-06-15",
        "booking_status": "completed",
        "notes": "Aisle seat with a power outlet.",
    },
    {
        "id": "booking_2027_adelaide_airport_bus",
        "trip_id": "trip_2027_adelaide_festival_week",
        "transport_id": "transport_2027_adl_metro_bus",
        "traveller_count": 2,
        "booking_date": "2027-01-05",
        "booking_status": "pending",
        "notes": "Fare paid on board.",
    },
)
