"""Demo data for the Student 3 transport service.

Derived columns (``duration_minutes`` on options, ``estimated_cost`` on bookings)
are intentionally omitted here; the repository fills them through the same
helpers used by the write endpoints so seeded rows cannot drift from records
created through the API.

Trip identifiers mirror the Student 1 seed trips so the integrated demo shows
transport attached to trips that already exist in the shared application.
"""

SEED_TRANSPORT_OPTIONS = (
    {
        "id": "transport_2026_qf401_mel_syd",
        "type": "flight",
        "provider": "Qantas",
        "origin": "Melbourne",
        "destination": "Sydney",
        "departure_time": "2026-10-02T06:00",
        "arrival_time": "2026-10-02T07:35",
        "price": 189.00,
        "capacity": 180,
        "availability_status": "available",
        "notes": "Morning departure with checked baggage included.",
    },
    {
        "id": "transport_2026_qf436_syd_mel",
        "type": "flight",
        "provider": "Qantas",
        "origin": "Sydney",
        "destination": "Melbourne",
        "departure_time": "2026-10-05T18:20",
        "arrival_time": "2026-10-05T20:00",
        "price": 205.50,
        "capacity": 180,
        "availability_status": "available",
        "notes": "Return leg for the Sydney long weekend.",
    },
    {
        "id": "transport_2026_vline_mel_geelong",
        "type": "train",
        "provider": "V/Line",
        "origin": "Melbourne",
        "destination": "Geelong",
        "departure_time": "2026-11-13T08:15",
        "arrival_time": "2026-11-13T09:20",
        "price": 12.40,
        "capacity": 320,
        "availability_status": "available",
        "notes": "Regional service departing Southern Cross.",
    },
    {
        "id": "transport_2026_skybus_mel_city",
        "type": "bus",
        "provider": "SkyBus",
        "origin": "Melbourne Airport",
        "destination": "Melbourne CBD",
        "departure_time": "2026-11-12T10:30",
        "arrival_time": "2026-11-12T11:15",
        "price": 23.50,
        "capacity": 60,
        "availability_status": "limited",
        "notes": "Departs every 10 minutes; seats are not allocated.",
    },
    {
        "id": "transport_2027_jl772_syd_hnd",
        "type": "flight",
        "provider": "Japan Airlines",
        "origin": "Sydney",
        "destination": "Tokyo",
        "departure_time": "2027-03-28T21:35",
        "arrival_time": "2027-03-29T05:55",
        "departure_utc_offset": 660,
        "arrival_utc_offset": 540,
        "price": 1245.00,
        "capacity": 244,
        "availability_status": "available",
        "notes": "Overnight service arriving early morning.",
    },
    {
        "id": "transport_2027_nex_narita_tokyo",
        "type": "train",
        "provider": "JR East",
        "origin": "Narita Airport",
        "destination": "Tokyo Station",
        "departure_time": "2027-03-29T07:45",
        "arrival_time": "2027-03-29T08:48",
        "price": 32.00,
        "capacity": 400,
        "availability_status": "available",
        "notes": "Narita Express with reserved seating.",
    },
    {
        "id": "transport_2026_jq790_syd_ool",
        "type": "flight",
        "provider": "Jetstar",
        "origin": "Sydney",
        "destination": "Gold Coast",
        "departure_time": "2026-12-20T07:10",
        "arrival_time": "2026-12-20T08:35",
        "price": 149.90,
        "capacity": 186,
        "availability_status": "limited",
        "notes": "School holiday peak; baggage is sold separately.",
    },
    {
        "id": "transport_2026_europcar_gold_coast",
        "type": "car_rental",
        "provider": "Europcar",
        "origin": "Gold Coast Airport",
        "destination": "Gold Coast Airport",
        "departure_time": "2026-12-20T09:00",
        "arrival_time": "2026-12-27T09:00",
        "price": 612.00,
        "capacity": 5,
        "availability_status": "available",
        "pricing_basis": "per_vehicle",
        "notes": "Seven day SUV hire priced per vehicle rather than per seat.",
    },
    {
        "id": "transport_2027_zqn_snow_shuttle",
        "type": "transfer",
        "provider": "Queenstown Snow Shuttle",
        "origin": "Queenstown Airport",
        "destination": "Queenstown Town Centre",
        "departure_time": "2027-07-10T14:20",
        "arrival_time": "2027-07-10T14:55",
        "price": 28.00,
        "capacity": 11,
        "availability_status": "available",
        "notes": "Ski and board carriage included in the fare.",
    },
    {
        "id": "transport_2026_sq232_syd_sin",
        "type": "flight",
        "provider": "Singapore Airlines",
        "origin": "Sydney",
        "destination": "Singapore",
        "departure_time": "2026-09-01T10:15",
        "arrival_time": "2026-09-01T16:35",
        "departure_utc_offset": 600,
        "arrival_utc_offset": 480,
        "price": 878.40,
        "capacity": 253,
        "availability_status": "sold_out",
        "notes": "Cabin fully booked; waitlist only.",
    },
    {
        "id": "transport_2026_spirit_geelong_devonport",
        "type": "ferry",
        "provider": "Spirit of Tasmania",
        "origin": "Geelong",
        "destination": "Devonport",
        "departure_time": "2026-06-11T19:30",
        "arrival_time": "2026-06-12T06:00",
        "price": 289.00,
        "capacity": 1400,
        "availability_status": "available",
        "notes": "Overnight crossing with a cabin upgrade available.",
    },
    {
        "id": "transport_2027_xpt_syd_bne",
        "type": "train",
        "provider": "NSW TrainLink",
        "origin": "Sydney",
        "destination": "Brisbane",
        "departure_time": "2027-01-21T06:10",
        "arrival_time": "2027-01-21T20:25",
        "price": 132.00,
        "capacity": 220,
        "availability_status": "cancelled",
        "notes": "Service withdrawn for track maintenance.",
    },
    {
        "id": "transport_2026_qf777_syd_per",
        "type": "flight",
        "provider": "Qantas",
        "origin": "Sydney",
        "destination": "Perth",
        "departure_time": "2026-08-18T09:05",
        "arrival_time": "2026-08-18T12:10",
        "departure_utc_offset": 600,
        "arrival_utc_offset": 480,
        "price": 425.00,
        "capacity": 236,
        "availability_status": "available",
        "notes": "Wi-Fi equipped for the workcation leg.",
    },
    {
        "id": "transport_2027_adl_metro_bus",
        "type": "bus",
        "provider": "Adelaide Metro",
        "origin": "Adelaide Airport",
        "destination": "Adelaide CBD",
        "departure_time": "2027-02-26T13:40",
        "arrival_time": "2027-02-26T14:15",
        "price": 6.50,
        "capacity": 45,
        "availability_status": "available",
        "notes": "JetBus J1 route; fares are tapped on board.",
    },
)
