SEED_TRIPS = (
    {
        "id": "trip_2026_sydney_long_weekend",
        "name": "Sydney Long Weekend",
        "destination": "Sydney",
        "start_date": "2026-10-02",
        "end_date": "2026-10-05",
        "traveller_count": 2,
        "status": "planned",
        "notes": "Focus on harbour views and easy walking routes.",
    },
    {
        "id": "trip_2026_melbourne_food_trail",
        "name": "Melbourne Food Trail",
        "destination": "Melbourne",
        "start_date": "2026-11-12",
        "end_date": "2026-11-16",
        "traveller_count": 4,
        "status": "draft",
        "notes": "Book the Queen Victoria Market tour if available.",
    },
    {
        "id": "trip_2027_tokyo_spring_visit",
        "name": "Tokyo Spring Visit",
        "destination": "Tokyo",
        "start_date": "2027-03-28",
        "end_date": "2027-04-04",
        "traveller_count": 2,
        "status": "planned",
        "notes": "Keep one free afternoon for shopping.",
    },
    {
        "id": "trip_2026_gold_coast_family_break",
        "name": "Gold Coast Family Break",
        "destination": "Gold Coast",
        "start_date": "2026-12-20",
        "end_date": "2026-12-27",
        "traveller_count": 5,
        "status": "active",
        "notes": "Need stroller-friendly activities.",
    },
    {
        "id": "trip_2027_queenstown_ski_escape",
        "name": "Queenstown Ski Escape",
        "destination": "Queenstown",
        "start_date": "2027-07-10",
        "end_date": "2027-07-16",
        "traveller_count": 3,
        "status": "planned",
        "notes": "Hire ski gear on day one.",
    },
    {
        "id": "trip_2026_singapore_stopover",
        "name": "Singapore Stopover",
        "destination": "Singapore",
        "start_date": "2026-09-01",
        "end_date": "2026-09-03",
        "traveller_count": 1,
        "status": "completed",
        "notes": "Carry-on only for fast airport transfers.",
    },
    {
        "id": "trip_2026_perth_workcation",
        "name": "Perth Workcation",
        "destination": "Perth",
        "start_date": "2026-08-18",
        "end_date": "2026-08-24",
        "traveller_count": 1,
        "status": "completed",
        "notes": "Quiet workspace needed mid-week.",
    },
    {
        "id": "trip_2026_hobart_weekend_escape",
        "name": "Hobart Weekend Escape",
        "destination": "Hobart",
        "start_date": "2026-06-11",
        "end_date": "2026-06-14",
        "traveller_count": 2,
        "status": "cancelled",
        "notes": "Cancelled after airline schedule change.",
    },
    {
        "id": "trip_2027_brisbane_city_break",
        "name": "Brisbane City Break",
        "destination": "Brisbane",
        "start_date": "2027-01-21",
        "end_date": "2027-01-24",
        "traveller_count": 2,
        "status": "draft",
        "notes": "Compare riverside hotel options.",
    },
    {
        "id": "trip_2027_adelaide_festival_week",
        "name": "Adelaide Festival Week",
        "destination": "Adelaide",
        "start_date": "2027-02-26",
        "end_date": "2027-03-03",
        "traveller_count": 2,
        "status": "planned",
        "notes": "Reserve festival tickets early.",
    },
)


SEED_ITINERARY_ITEMS = (
    {
        "id": "item_2026_sydney_harbour_walk",
        "trip_id": "trip_2026_sydney_long_weekend",
        "date": "2026-10-03",
        "start_time": "09:00",
        "end_time": "11:00",
        "title": "Harbour Walk",
        "location": "Circular Quay",
        "description": "Morning harbour loop with coffee stop.",
        "category": "activity",
        "notes": "Weather dependent.",
    },
    {
        "id": "item_2026_melbourne_market_lunch",
        "trip_id": "trip_2026_melbourne_food_trail",
        "date": "2026-11-13",
        "start_time": "12:00",
        "end_time": "14:00",
        "title": "Market Lunch",
        "location": "Queen Victoria Market",
        "description": "Sample local produce and casual lunch stalls.",
        "category": "meal",
        "notes": "Arrive hungry.",
    },
    {
        "id": "item_2027_tokyo_hotel_checkin",
        "trip_id": "trip_2027_tokyo_spring_visit",
        "date": "2027-03-28",
        "start_time": "15:00",
        "end_time": "16:00",
        "title": "Hotel Check-in",
        "location": "Shinjuku",
        "description": "Check in and store luggage before evening walk.",
        "category": "accommodation",
        "notes": "Confirm late check-in policy.",
    },
    {
        "id": "item_2026_gold_coast_theme_park",
        "trip_id": "trip_2026_gold_coast_family_break",
        "date": "2026-12-22",
        "start_time": "10:00",
        "end_time": "17:00",
        "title": "Theme Park Day",
        "location": "Coomera",
        "description": "Family rides and shows with meal breaks.",
        "category": "activity",
        "notes": "Pack spare clothes for the kids.",
    },
    {
        "id": "item_2027_queenstown_airport_transfer",
        "trip_id": "trip_2027_queenstown_ski_escape",
        "date": "2027-07-10",
        "start_time": "13:30",
        "end_time": "14:15",
        "title": "Airport Transfer",
        "location": "Queenstown Airport",
        "description": "Shared shuttle to the apartment.",
        "category": "transport",
        "notes": "Book skis as extra luggage.",
    },
    {
        "id": "item_2026_singapore_hawker_dinner",
        "trip_id": "trip_2026_singapore_stopover",
        "date": "2026-09-02",
        "start_time": "18:30",
        "end_time": "20:00",
        "title": "Hawker Centre Dinner",
        "location": "Lau Pa Sat",
        "description": "Quick dinner before the night safari shuttle.",
        "category": "meal",
        "notes": "Bring cash for smaller stalls.",
    },
    {
        "id": "item_2026_perth_workspace_booking",
        "trip_id": "trip_2026_perth_workcation",
        "date": "2026-08-19",
        "start_time": "08:30",
        "end_time": "17:00",
        "title": "Coworking Day Pass",
        "location": "Perth CBD",
        "description": "Dedicated workspace for client calls.",
        "category": "note",
        "notes": "Ask for a monitor on arrival.",
    },
    {
        "id": "item_2026_hobart_refund_followup",
        "trip_id": "trip_2026_hobart_weekend_escape",
        "date": "2026-06-12",
        "start_time": None,
        "end_time": None,
        "title": "Refund Follow-up",
        "location": None,
        "description": "Contact airline support about refund timing.",
        "category": "other",
        "notes": "Keep booking reference handy.",
    },
    {
        "id": "item_2027_brisbane_river_cruise",
        "trip_id": "trip_2027_brisbane_city_break",
        "date": "2027-01-22",
        "start_time": "17:00",
        "end_time": "18:00",
        "title": "River Cruise",
        "location": "South Bank",
        "description": "Sunset cruise before dinner.",
        "category": "activity",
        "notes": "Reserve seats on the upper deck.",
    },
    {
        "id": "item_2027_adelaide_festival_opening",
        "trip_id": "trip_2027_adelaide_festival_week",
        "date": "2027-02-27",
        "start_time": "19:00",
        "end_time": "21:30",
        "title": "Festival Opening Night",
        "location": "Adelaide Festival Centre",
        "description": "Attend the opening performance.",
        "category": "activity",
        "notes": "Collect tickets from the box office.",
    },
)
